apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ryanj23-ryanj23-poi-map-app-dev
  annotations:
    argocd/app-name: ryanj23-ryanj23-poi-map-app-dev
    backstage.io/kubernetes-id: ryanj23-ryanj23-poi-map-app-dev
    backstage.io/kubernetes-namespace: ryanj23
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=ryanj23-ryanj23-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/ryanj23-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/ryanj23/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/ryanj23/deployments/ryanj23-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/ryanj23-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://ryanj23-poi-map-app-ryanj23.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-ryanj23
  consumesApis:
    - gateway-api-ryanj23
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-ryanj23
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ryanj"
